name: maps
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  http: ^1.5.0
  latlong2: ^0.9.1
  location: ^8.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/map_styles/night_map_style.json
    - assets/Images/icons8-marker-100.png
    - assets/Images/
